/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/myPage/AboutComponent.vue')['default']
    CardComponent: typeof import('./src/components/util/CardComponent.vue')['default']
    CardSectionComponent: typeof import('./src/components/util/CardSectionComponent.vue')['default']
    FooterComponent: typeof import('./src/components/Layout/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/Layout/HeaderComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/Layout/NavbarComponent.vue')['default']
    PiChartComponent: typeof import('./src/components/myPage/PiChartComponent.vue')['default']
    PostCardComponent: typeof import('./src/components/util/PostCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticComponent: typeof import('./src/components/myPage/StaticComponent.vue')['default']
    TagComponent: typeof import('./src/components/util/TagComponent.vue')['default']
  }
}
