/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./src/components/myPage/AboutComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    CommentComponent: typeof import('./src/components/util/post/CommentComponent.vue')['default']
    CommentSection: typeof import('./src/components/section/CommentSection.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FooterComponent: typeof import('./src/components/Layout/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/Layout/HeaderComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    ModalComponent: typeof import('./src/components/util/ModalComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/Layout/NavbarComponent.vue')['default']
    NewRoutineComponent: typeof import('./src/components/myRoutine/NewRoutineComponent.vue')['default']
    PostCardComponent: typeof import('./src/components/util/post/PostCardComponent.vue')['default']
    PostCardSectionComponent: typeof import('./src/components/util/post/PostCardSectionComponent.vue')['default']
    PostSummaryComponent: typeof import('./src/components/util/post/PostSummaryComponent.vue')['default']
    ProfileComponent: typeof import('./src/components/ProfileComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    SignUpComponent: typeof import('./src/components/SignUpComponent.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    StaticComponent: typeof import('./src/components/myPage/StaticComponent.vue')['default']
    TagComponent: typeof import('./src/components/util/TagComponent.vue')['default']
    TagModalComponent: typeof import('./src/components/util/tag/TagModalComponent.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    VideoComponent: typeof import('./src/components/util/post/VideoComponent.vue')['default']
    VideoInfoComponent: typeof import('./src/components/util/VideoInfoComponent.vue')['default']
  }
}
